services:
  - type: web
    name: caresphere-api
    runtime: python
    region: oregon
    rootDir: HealthCare_backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.13.0
